
import img1 from './assets/fast-food.png';
import img2 from './assets/waffi.png';
import img3 from './assets/crepe.jpg';
import img4 from './assets/pan-cake.png';
import img5 from './assets/hoka.jpg';
import img6 from './assets/juice.png';
import img7 from './assets/hot-drinks.png';
import img8 from './assets/moheto.png';
import img9 from './assets/ice-coffee.avif';

export const item = [
  {
    id: 1,
    title: "الوجبات السريعه",
    img: img1,
    info: {
      item1: {
        price: {
          pric1: 3500,
          pric2: 3500,
          pric3: 4000,
          pric4: 4500,
          pric5: 5000,
          pric6: 3500,
          pric7: 3500,
          pric8: 1500,
          pric9: 1500,
          pric10: 2000,
          pric11: 2000,
          pric12: 2000,
          pric13: 2000,
          pric14: 1500,
        },
        subtitle: {
          sub1: "بركر لحم",
          sub2: "بركر دجاج",
          sub3: "بركر بالجبن",
          sub4: "وجبه بركر",
          sub5: "وجبه بركر بالجبن",
          sub6: "زنكر",
          sub7: "سكالوب",
          sub8: "فنكر",
          sub9: "فنكر بالصلصه",
          sub10: "فطائر لحم",
          sub11: "فطائر دجاج",
          sub12: "فطائر جبن",
          sub13: "فطائر خضروات",
          sub14: "كرواسون",
        },
      },
    },
  },
  {
    id: 2,
    title: "وافل",
    img: img2,
    info: {
      item1: {
        price: {
          pric1: 4000,
          pric2: 4000,
          pric3: 4000,
          pric4: 4000,
          pric5: 5000,
          pric6: 5000,
        },
        subtitle: {
          sub1: "كلاسك وافل",
          sub2: "لوتس وافل",
          sub3: "اوريو وافل",
          sub4: "وايت وافل",
          sub5: "فواكه وافل",
          sub6: "مكسرات وافل",
        },
      },
    },
  },
  {
    id: 3,
    title: "كريبات",
    img: img3,
    info: {
      item1: {
        price: {
          pric1: 4000,
          pric2: 4000,
          pric3: 4000,
          pric4: 4000,
          pric5: 5000,
        },
        subtitle: {
          sub1: "كلاسك كريب",
          sub2: "لوتس كريب",
          sub3: "اوريو كريب",
          sub4: "كريب فواكه",
          sub5: "لوسيل كريب",
        },
      },
    },
  },
  {
    id: 4,
    title: "بان كيك",
    img: img4,
    info: {
      item1: {
        price: {
          pric1: 4000,
          pric2: 5000,
          pric3: 5000,
          pric4: 5000,
          pric5: 7000,
          pric6: 5000,
          pric7: 5000,
          pric8: 5000,
        },
        subtitle: {
          sub1: "بان كيك",
          sub2: "سبشل بان كيك",
          sub3: "بان كيك كلاسك",
          sub4: "بان كيك مكسرات",
          sub5: "بان كيك فواكه",
          sub6: "بان كيك لوتس",
          sub7: "بان كيك اوريو",
          sub8: "بان كيك بستاشيو",
        },
      },
    },
  },
  {
    id: 5,
    title: "نراكيل",
    img: img5,
    info: {
      item1: {
        price: {
          pric1: 5000,
          pric2: 5000,
          pric3: 5000,
          pric4: 5000,
        },
        subtitle: {
          sub1: "علج ونعناع",
          sub2: "ليمون ونعناع",
          sub3: "انكليزي",
          sub4: "تفاحتين",
        },
      },
    },
  },
  {
    id: 6,
    title: "العصائر",
    img: img6,
    info: {
      item1: {
        price: {
          pric1: 3000,
          pric2: 5000,
          pric3: 4000,
          pric4: 4000,
          pric5: 4000,
          pric6: 6000,
          pric7: 4000,
          pric8: 5000,
          pric9: 5000,
          pric10: 5000,
          pric11: 5000,
          pric12: 4000,
          pric13: 5000,
          pric14: 5000,
          pric15: 4000,
          pric16: 4000,
          pric17: 4000,
          pric18: 4000,
          pric19: 4000,
          pric20: 5000,
          pric21: 5000,
          pric22: 4000,
          pric23: 5000,
          pric24: 5000,
          pric25: 5000,
          pric26: 4000,
          pric27: 4000,
          pric28: 4000,
          pric29: 5000,
          pric30: 5000,
          pric31: 5000,
        },
        subtitle: {
          sub1: "عصائر فرش كافه الانواع",
          sub2: "فتنس",
          sub3: "سبايدرمان",
          sub4: "باتمان",
          sub5: "بدون جاذبيه",
          sub6: "مجوهرات المريخ",
          sub7: "شاني ماني",
          sub8: "عالم ثاني",
          sub9: "روبوت",
          sub10: "ناسا",
          sub11: "طبقه الاوزون",
          sub12: "عطارد",
          sub13: "المريخ",
          sub14: "رافييلو",
          sub15: "توتو",
          sub16: "زحل",
          sub17: "الزهره",
          sub18: "سريلاك",
          sub19: "الشايب",
          sub20: "كلوبال",
          sub21: "هابل",
          sub22: "جيمس ويت",
          sub23: "سينما",
          sub24: "ترانسفومرمو",
          sub25: "بكبانك",
          sub26: "عوارقلب",
          sub27: "ليدي",
          sub28: "طوكيو",
          sub29: "غاليلو",
          sub30: "كاكارين",
          sub31: "درب اللباله",
        },
      },
    },
  },
  {
    id: 7,
    title: "مشروبات ساخنه",
    img: img7,
    info: {
      item1: {
        price: {
          pric1: 2000,
          pric2: 2000,
          pric3: 2000,
          pric4: 3000,
          pric5: 3000,
          pric6: 3000,
          pric7: 3000,
          pric8: 2000,
          pric9: 2000,
          pric10: 1000,
        },
        subtitle: {
          sub1: "كابتشينو",
          sub2: "امريكانو",
          sub3: "اسبريسو",
          sub4: "اسبريسو دبل",
          sub5: "لاتيه",
          sub6: "سبانيش لاتيه",
          sub7: "بستاشيو لاتيه",
          sub8: "نسكافيه بلاك",
          sub9: "نسكافيه",
          sub10: "شاي",
        },
      },
    },
  },
  {
    id: 8,
    title: "الموهيتو",
    img: img8,
    info: {
      item1: {
        price: {
          pric1: 3000,
          pric2: 3000,
          pric3: 3000,
          pric4: 3000,
          pric5: 3000,
          pric6: 3000,
          pric7: 3000,
          pric8: 4000,
          pric9: 3000,
          pric10: 3000,
          pric11: 3000,
        },
        subtitle: {
          sub1: "ليمون ونعناع",
          sub2: "بلوكارسكو",
          sub3: "بلاك بيري",
          sub4: "ببل كام",
          sub5: "موهيتو فراوله",
          sub6: "موهيتو شعر بنات",
          sub7: "بلو بيري",
          sub8: "لوسيل",
          sub9: "موهيتو كرز",
          sub10: "باشن فروت",
          sub11: "موهيتو كيوي"
        },
      },
    },
  },
  {
    id: 9,
    title: "ايس كوفي",
    img: img9,
    info: {
      item1: {
        price: {
          pric1: 3000,
          pric2: 3000,
          pric3: 3000,
          pric4: 3000,
          pric5: 2000,
        },
        subtitle: {
          sub1: "ايس لاتيه",
          sub2: "ايس كابتشينو",
          sub3: "ايس سبانش لاتيه",
          sub4: "ايس لاتيه",
          sub5: "ايس تي",
        },
      },
    },
  },
];
